version: "3"

services:
  subquery-node-oak-task-service:
    image: onfinality/subql-node:v0.29.0
    restart: always
    environment:
      DB_USER: 
      DB_PASS: 
      DB_DATABASE:
      DB_HOST: 
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - -f=/app
      - --db-schema=public
      - --scale-batch-size=false
      - --batch-size=20
      #- --force-clean=true
      # - --log-level=debug
      # - --debug
      # - --profiler=true
