version: "3"

services:
  subquery-polkadot:
    image: onfinality/subql-node:v1.4.1
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: Dev123!@#
      DB_DATABASE: dev-polkadot-xcm
      DB_HOST: 16.163.5.216
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - -f=/app
      - --db-schema=public
      - --scale-batch-size=false
      - --batch-size=20
      #- --force-clean=true
      - --log-level=debug
      # - --debug
      # - --profiler=true
