specVersion: 0.2.0
description: "XCM indexer"
repository: ""
schema:
  file: ./schema.graphql
network:
  endpoint: 'wss://kusama.api.onfinality.io/public-ws'
  genesisHash: '0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe'
  dictionary: https://api.subquery.network/sq/subquery/kusama-dictionary
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 7468792
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
        - handler: handleCall
          kind: substrate/CallHandler
        # - handler: handleHrmpEvents
        #   kind: substrate/EventHandler
        #   filter: 
        #     module: hrmp
        # - handler: handleXcmPalletExtrinsics
        #   kind: substrate/CallHandler
        #   filter: 
        #     module: xcmPallet